---
dependency:
  name: galaxy
driver:
  name: docker

lint: |
  yamllint .
  ansible-lint
platforms:
  - name: centos_7
    image: centos:7
    privileged: true
    command: /usr/sbin/init
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    env:
      ANSIBLE_USER: ansible
      SUDO_GROUP: wheel
      DEPLOY_GROUP: deployer
      container: docker

  - name: debian_bullseye_11
    image: debian:bullseye
    privileged: true
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    env:
      ANSIBLE_USER: ansible
      SUDO_GROUP: sudo
      DEPLOY_GROUP: deployer
      container: docker
provisioner:
  name: ansible
verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    # - dependency
    - syntax
    - create
    # - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    - destroy
