---
- name: Converge
  hosts: all
  tasks:
    - name: "Include netology_devops_vector"
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
